### ISSUE TITLE
I updated Read me  for astro users

### ISSUE THREAD

**Issue by UnschooledGamer** [sanikava/OpMongo#3]
@sanikava so please update it

**Comment by sanikava** [comment]
> @sanikava so please update it

@UnschooledGamer what update you need?

**Comment by UnschooledGamer** [comment]
> > @sanikava so please update it
> 
> @UnschooledGamer what update you need?
Add this line 👇
const { OP } = require("/data/data/com.astrosohu/files/usr/lib/node_modules/opmongo"); //use this if you are using this in Astro nodeJS

**Comment by sanikava** [comment]
> > > @sanikava so please update it
> > 
> > @UnschooledGamer what update you need?
> Add this line 👇
> const { OP } = require("/data/data/com.astrosohu/files/usr/lib/node_modules/opmongo"); //use this if you are using this in Astro nodeJS

lol ok

**Comment by sanikava** [comment]
can you push your update?
